/*******************************************************************************
* FILENAME: project.h
* 
* PSoC Creator  3.2
*
* DESCRIPTION:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "AD_L.h"
#include "AD_L_aliases.h"
#include "AD_H.h"
#include "AD_H_aliases.h"
#include "SIA.h"
#include "SIA_aliases.h"
#include "RD.h"
#include "RD_aliases.h"
#include "SIP.h"
#include "SIP_aliases.h"
#include "SE1.h"
#include "SE1_aliases.h"
#include "AH_reg.h"
#include "AL_reg.h"
#include "STATE.h"
#include "SE2.h"
#include "SE2_aliases.h"
#include "SE3.h"
#include "SE3_aliases.h"
#include "SE0.h"
#include "SE0_aliases.h"
#include "IDX.h"
#include "IDX_aliases.h"
#include "WR.h"
#include "WR_aliases.h"
#include "SPI_1.h"
#include "SPI_1_SPI_UART.h"
#include "SPI_1_PINS.h"
#include "SPI_1_SPI_UART_PVT.h"
#include "SPI_1_PVT.h"
#include "SPI_1_BOOT.h"
#include "LED1.h"
#include "LED1_aliases.h"
#include "SPI_CS.h"
#include "SPI_CS_aliases.h"
#include "BYTE.h"
#include "BYTE_aliases.h"
#include "CD.h"
#include "CD_aliases.h"
#include "isr_1.h"
#include "SPI_1_SCBCLK.h"
#include "SPI_1_sclk_m.h"
#include "SPI_1_sclk_m_aliases.h"
#include "SPI_1_miso_m.h"
#include "SPI_1_miso_m_aliases.h"
#include "SPI_1_mosi_m.h"
#include "SPI_1_mosi_m_aliases.h"
#include "SPI_1_ss0_m.h"
#include "SPI_1_ss0_m_aliases.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

